FROM node:20.12.0-alpine3.19

WORKDIR /app
COPY ./ ./
ARG NEXTAUTH_SECRET
ENV NEXTAUTH_SECRET ${NEXTAUTH_SECRET}
ARG DATABASE_URL
ENV DATABASE_URL ${DATABASE_URL}
RUN npm install -g npm@10.5.0 && \
	npm ci --omit=dev && \
	npx prisma generate && \
	npm run build && \
	npm run prisma:push
CMD ["npm", "run", "start"]
