steps:
  # アプリビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}",
        "--build-arg",
        "DATABASE_URL=${_DATABASE_URL}",
        "--build-arg",
        "RESEND_API_KEY=${_RESEND_API_KEY}",
        "--build-arg",
        "SERVER_API_KEY=${_SERVER_API_KEY}",
        "--build-arg",
        "R2_ENDPOINT=${_R2_ENDPOINT}",
        "--build-arg",
        "R2_SECRET_ACCESS_KEY=${_R2_SECRET_ACCESS_KEY}",
        "--build-arg",
        "R2_ACCESS_KEY_ID=${_R2_ACCESS_KEY_ID}",
        "--build-arg",
        "R2_BUCKET=${_R2_BUCKET}",
        "-t",
        "${_APP_IMAGE_NAME}:${COMMIT_SHA}",
        "-f",
        "docker/app/Dockerfile.prod",
        "."
      ]
  # アプリpush
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_APP_IMAGE_NAME}:${COMMIT_SHA}"]
  # アプリデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_APP_SERVICE_NAME}",
        "--image",
        "${_APP_IMAGE_NAME}:${COMMIT_SHA}",
        "--region",
        "asia-northeast1",
        "--allow-unauthenticated"
      ]
  # アプリの古いArtifact Registryのイメージを削除
  - name: "asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest"
    args: ["--repo=${_APP_IMAGE_NAME}", "--keep=3", "--tag-filter-any=.*"]
  # アカウント削除バッチビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "DATABASE_URL=${_DATABASE_URL}",
        "-t",
        "${_APP_IMAGE_NAME}:${COMMIT_SHA}",
        "-f",
        "docker/batch/delete-noverified-account/Dockerfile.prod",
        "."
      ]
  # アカウント削除バッチpush
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_DELETE_NOVERIFIED_ACCOUNT_BATCH_IMAGE_NAME}:${COMMIT_SHA}"]
  # # アカウント削除バッチデプロイ
  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   entrypoint: gcloud
  #   args:
  #     [
  #       "run",
  #       "deploy",
  #       "${_DELETE_NOVERIFIED_ACCOUNT_BATCH_SERVICE_NAME}",
  #       "--image",
  #       "${_DELETE_NOVERIFIED_ACCOUNT_BATCH_IMAGE_NAME}:${COMMIT_SHA}",
  #       "--region",
  #       "asia-northeast1",
  #       "--allow-unauthenticated"
  #     ]
  # # 古いArtifact Registryのイメージを削除
  # - name: "asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest"
  #   args: ["--repo=${_DELETE_NOVERIFIED_ACCOUNT_BATCH_IMAGE_NAME}", "--keep=3", "--tag-filter-any=.*"]
substitutions:
  _APP_IMAGE_NAME: "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/allergynav/production"
  _APP_SERVICE_NAME: "allergynav"
  _DELETE_NOVERIFIED_ACCOUNT_BATCH_IMAGE_NAME: "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/allergynav/production"
  _DELETE_NOVERIFIED_ACCOUNT_BATCH_SERVICE_NAME: "delete-noverified-account"
