services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.dev
    tty: true
    stdin_open: true
    init: true
    environment:
      TZ: Asia/Tokyo
      CHOKIDAR_USEPOLLING: 1
      HOST: 0.0.0.0
    ports:
      - "10111:10111"
      - "10113:5555"
    working_dir: /app/
    volumes:
      - ./:/app/

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile.dev
    tty: true
    stdin_open: true
    ports:
      - "10112:8080"
    environment:
      TZ: Asia/Tokyo
      COCKROACH_USER: root
      COCKROACH_PASSWORD: root
    command: start-single-node --insecure
