DROP SCHEMA IF EXISTS dev;

CREATE SCHEMA dev DEFAULT CHARACTER
SET
	utf8mb4 COLLATE utf8mb4_general_ci;

USE dev;

CREATE TABLE
	store_groups (
		id INT(10) NOT NULL AUTO_INCREMENT,
		name VARCHAR(40) NOT NULL,
		description TEXT NOT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	store_group_histories (
		id INT(10) NOT NULL AUTO_INCREMENT,
		ip VARCHAR(40) NOT NULL,
		store_group_id INT(10),
		name VARCHAR(40),
		description TEXT,
		deleted BOOLEAN,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	stores (
		id INT(10) NOT NULL AUTO_INCREMENT,
		name VARCHAR(40) NOT NULL,
		address VARCHAR(100) NOT NULL,
		store_group_id INT(10) DEFAULT NULL,
		description TEXT NOT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	store_histories (
		id INT(10) NOT NULL AUTO_INCREMENT,
		ip VARCHAR(40) NOT NULL,
		store_id INT(10),
		name VARCHAR(40),
		address VARCHAR(100),
		store_group_id INT(10),
		description TEXT,
		deleted BOOLEAN,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	merge_stores (
		from_id INT(10) NOT NULL,
		to_id INT(10) NOT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(from_id, to_id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	menu (
		id INT(10) NOT NULL AUTO_INCREMENT,
		name VARCHAR(40) NOT NULL,
		store_id INT(10) DEFAULT NULL,
		store_group_id INT(10) DEFAULT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	menu_histories (
		id INT(10) NOT NULL AUTO_INCREMENT,
		ip VARCHAR(40) NOT NULL,
		menu_id INT(10),
		name VARCHAR(40),
		store_id INT(10),
		store_group_id INT(10),
		deleted BOOLEAN,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	image (
		id INT(10) NOT NULL AUTO_INCREMENT,
		menu_id INT(10) DEFAULT NULL,
		store_id INT(10) DEFAULT NULL,
		store_group_id INT(10) DEFAULT NULL,
		file_name VARCHAR(40) NOT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	comments (
		id INT(10) NOT NULL AUTO_INCREMENT,
		title VARCHAR(40) NOT NULL,
		content TEXT NOT NULL,
		store_id INT(10) DEFAULT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	comment_histories (
		id INT (10) NOT NULL AUTO_INCREMENT,
		ip VARCHAR(40) NOT NULL,
		comment_id INT(10),
		title VARCHAR(40),
		content TEXT,
		store_id INT(10),
		deleted BOOLEAN,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	allergens (
		id VARCHAR(40) NOT NULL,
		name VARCHAR(40) NOT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	allergen_options (
		id INT(10) NOT NULL AUTO_INCREMENT,
		allergen_id VARCHAR(40) NOT NULL,
		name VARCHAR(40) NOT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	menu_allergens (
		allergen_id VARCHAR(40) NOT NULL,
		menu_id INT(10) NOT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(allergen_id, menu_id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	menu_allergen_options (
		allergen_option_id INT(10) NOT NULL,
		menu_id INT(10) NOT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(allergen_option_id, menu_id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	users (
		id INT (10) NOT NULL AUTO_INCREMENT,
		username VARCHAR(40) NOT NULL,
		email VARCHAR(100) NOT NULL UNIQUE,
		password VARCHAR(100) NOT NULL,
		role INT(10) DEFAULT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE
	roles (
		id INT (10) NOT NULL AUTO_INCREMENT,
		name VARCHAR(40) NOT NULL,
		deleted BOOLEAN NOT NULL DEFAULT FALSE,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY(id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

INSERT INTO
	allergens (id, name)
VALUES
	("egg", "卵"),
	("milk", "乳製品"),
	("wheat", "小麦"),
	("shrimp", "エビ"),
	("crab", "カニ"),
	("soba", "そば"),
	("peanut", "落花生");

INSERT INTO
	roles (name)
VALUES
	("admin");
