FROM node:20.12.0-alpine3.19

WORKDIR /batch
COPY ./ ./

ARG DATABASE_URL
ENV DATABASE_URL ${DATABASE_URL}

RUN npm install -g npm@10.5.0 && \
	npm ci --omit=dev && \
	npx prisma generate
CMD ["npm", "run", "tsnode" "--" "batch/delete-noverified-account/batch.ts"]
