FROM node:20.12.0-alpine3.19

WORKDIR /app
COPY ./ ./

ARG DATABASE_URL
ENV DATABASE_URL ${DATABASE_URL}

ARG SERVER_API_KEY
ENV SERVER_API_KEY ${SERVER_API_KEY}

RUN npm install -g npm@10.5.0 && \
	npm ci --omit=dev && \
	npx prisma generate && \
	npm run build
CMD ["npm", "run", "start"]
